"""empty message

Revision ID: 527488dc4578
Revises: d5d57445b2c5
Create Date: 2024-09-21 16:10:57.222326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '527488dc4578'
down_revision = 'd5d57445b2c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
